### ISSUE TITLE
`wmic` deprecation warning

### ISSUE THREAD

**Issue by jonahgeorge** [talesluna/rust-printers#10]
Was debugging printing on Windows and ran across this deprecation warning:
<img width="714" alt="CleanShot 2022-12-31 at 15 38 41@2x" src="https://user-images.githubusercontent.com/2058205/210157644-a8bcccf2-3051-4b10-bd1a-36cb824cb50a.png">
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/wmic

I don't have much experience with Windows development, but I'm curious if using `Get-Printer` would be better:
https://learn.microsoft.com/en-us/powershell/module/printmanagement/get-printer?view=windowsserver2022-ps

**Comment by talesluna** [comment]
Fixed in #13 adopting powershell like you proposed in #9
