### ISSUE TITLE
Specify page size 

### ISSUE THREAD

**Issue by JuliDi** [talesluna/rust-printers#11]
Hi,
Is it possible to specify the page size of the file to print? Or somehow pass parameters to the printer function?
Maybe I've simply overlooked something in the code...

**Comment by talesluna** [comment]
Hi @JuliDi , Thanks for your contributing.

Sounds a good idea implements printing options on utility. I changed the target of your opened PR #12 to a isolated branch to study more about this and equalize with the most recent release (1.2.0) that has replaced wmic and lpr to powershell utilities for windows.

Soon I should bring a definitive release with your contribution

**Comment by JuliDi** [comment]
Sounds great, thank you!
