### ISSUE TITLE
incorrect result of PDF print_file 

### ISSUE THREAD

**Issue by ulvido** [talesluna/rust-printers#14]
Directly print command works awesome but output paper has scrambled characters on it. How can we resolve this. Thank you.

**NOTE:** .txt files prints fine but non-latin characters appears different. 
```rust
use printers;

fn main() {
    let samsung_printer = printers::get_printer_by_name("SEC001599CE908B").unwrap();
    
    samsung_printer.print_file("report.pdf");
    samsung_printer.print_file("readme.txt");
}
```

#### PDF result for example 
![IMG_20230503_114818](https://user-images.githubusercontent.com/27722274/235871617-5ad11fd3-be8a-4470-803c-00d9b58adada.jpg)

**Comment by jonahgeorge** [comment]
What operating system are you on? 

I spent some time looking at how other libraries deal with this and if you're on Windows, it appears that the common way of solving printing PDFs correctly is to delegate the printing the PDF to another utility such as SumatraPDF:

- https://github.com/artiebits/pdf-to-printer
- https://github.com/artiebits/pdf-to-printer/blob/master/src/print/print.ts#L28-L38

**Comment by ulvido** [comment]
Windows 10. Thank you.
![image](https://user-images.githubusercontent.com/27722274/236117819-435715e3-b8ca-4d1c-bd71-8f243190c613.png)

**Comment by ulvido** [comment]
> What operating system are you on?
> 
> I spent some time looking at how other libraries deal with this and if you're on Windows, it appears that the common way of solving printing PDFs correctly is to delegate to another utility such as [SumatraPDF](https://github.com/sumatrapdfreader/sumatrapdf):
> 
> * https://github.com/artiebits/pdf-to-printer
> * https://github.com/artiebits/pdf-to-printer/blob/master/src/print/print.ts#L28-L38

sumatrapdf totally satisfied my need. thank you very much. quick example code:

```rust
use std::process::Command;

fn main() {
    Command::new(".\\sumatrapdf\\SumatraPDF-3.4.6-64.exe") // portable sumartapdf
        .arg("-print-to")
        .arg("SEC001599CE908B") // printer name
        .arg("-silent") // direct print
        .arg("report.pdf") // pdf file
        .output()
        .unwrap();
}
```
