### ISSUE TITLE
Does this crate have the ability to print pdf in windows?

### ISSUE THREAD

**Issue by ragoso** [talesluna/rust-printers#16]
On macos it prints well, however on windows, the file is printed in text mode and not in PDF.

**Comment by jonahgeorge** [comment]
You might be interested in this thread- shows an example of PDF printing on Windows: https://github.com/talesluna/rust-printers/issues/14

A future modification to this library might be to bundle Sumatra as [alfianlensundev/tauri-plugin-printer](https://github.com/alfianlensundev/tauri-plugin-printer) currently does.
