### ISSUE TITLE
How to print image

### ISSUE THREAD

**Issue by semmywong** [talesluna/rust-printers#18]
how to print image. I try the `print_file`, but no work.  just print text file.

```
printer.print_file("C:\\Users\\Administrator\\Documents\\01.jpg", None);
```

**Comment by trembel** [comment]
I think this is the same issue as here https://github.com/talesluna/rust-printers/issues/16.

**Comment by talesluna** [comment]
For unix (cups), just send file or buffer
For windows unfortunelly depends if printer firmware can detect the RAW data filetype.
