### ISSUE TITLE
The tspl instruction cannot be parsed

### ISSUE THREAD

**Issue by qofjoo** [talesluna/rust-printers#19]
use printers;

fn main() {
    let printer = printers::get_printer_by_name("DL-888T").unwrap();
    let mut data: Vec<u8> = vec![];
    let mydata1 = String::from("S0056M1234-A001");
    let msg1 = mydata1.into_bytes();

    data.extend(b"SIZE 4,1\n");
    data.extend(b"GAP 0,0\n");
    data.extend(b"DIRECTION 1\n");
    data.extend(b"HOME\n");
    data.extend(b"CLS\n");
    data.extend(b"TEXT 120,10,\"0\",0,1,1,\"");
    data.extend(msg1);
    data.extend(b"\"\n");
    data.extend(b"BARCODE 120,50,\"128\",100,1,0,2,2,\"123456abcd123456\"\n");
    data.extend(b"PRINT 1\r\n");

    printer.print(&data, None).unwrap();
}The above is my code, please ask why after I run it, what is printed is the TSPL command, not the pattern formed by the command. We run it successfully on linux, but the problem I mentioned occurs on windows, can you know what is the problem

**Comment by talesluna** [comment]
Theres no support for TSPL for now. The content sent to printing is only bytes or file to process as is
