### ISSUE TITLE
Error: "double free or corruption (out) " while running on linux.

### ISSUE THREAD

**Issue by Marlonzao** [talesluna/rust-printers#22]
I'm new to rust so I'm sorry if this is a trivial problem, but:

```
use printers;

fn main() {
    let _printers = printers::get_printers();
}
```

When I run **cargo run** on this code this error is thrown: 

![image](https://github.com/talesluna/rust-printers/assets/17887269/d450b555-8ae4-4aa4-86c5-323b01ab05fc)

I have CUPS installed and running.
I'm on ubuntu.

**Comment by talesluna** [comment]
Fixed on #27
