### ISSUE TITLE
index out of bounds: the len is 0 but the index is 1

### ISSUE THREAD

**Issue by zhangwuqiao** [talesluna/rust-printers#5]
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1', C:\Users\zhangby\.cargo\registry\src\github.com-1ecc6299db9ec823\printers-1.0.2\src\windows.rs:27:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\printer.exe` (exit code: 101)

**Comment by downace** [comment]
Looks like there is an error in this command:

https://github.com/talesluna/rust-printers/blob/a1b29ea23b03368d93b94390161070070f7188e5/src/windows.rs#L11-L13

`wmic printer get 'DriverName, Name'` - error
`wmic printer get 'DriverName,Name'` - ok
