### ISSUE TITLE
[bug] one error,Thanks bro.

### ISSUE THREAD

**Issue by cheng-io** [talesluna/rust-printers#8]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/40415260/205514592-e91c7acb-cb28-4baa-91ef-d15889e258a1.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/40415260/205514603-60457bce-cd67-4001-9619-3fc5df8c5b11.png">

**Comment by cayweb778** [comment]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/40415260/205515747-a5887850-edc5-41d8-8844-56622cc290ef.png">
It is good.

**Comment by talesluna** [comment]
Thanks for contributing @cheng-io 

This issue are fixed by PR #13 (tag v1.2.0)
